// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sixvweywwzcxtofqimle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpeHZ3ZXl3d3pjeHRvZnFpbWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDM4MTcsImV4cCI6MjA1OTI3OTgxN30.egX9Uaj3huh094vlgCgdXZlh0JzVz2qNDNUQJCZw7xQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);